--Marketing Campaign Performance & Customer Analytics Case Study

--------------------Business Scenario

-----------2market is running multiple marketing campaigns across:

-- Bulkmail
-- Twitter
-- Instagram
-- Facebook
-- Brochure

--Management wants to understand:

--* Which campaigns generate the most revenue
--* Which customer segments respond the most
--* Where marketing budget should be optimised

--two data files used in the analysis
select * from marketing_data;
select * from ad_data;

------------------------ Customer & Revenue Overview

--1. What is the total revenue generated by all customers?
select  sum(amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm) AS total_revenue

from marketing_data;



--2. What is the average spending per customer?
select round(avg(amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm),2) AS avg_revenue_per_customer

from marketing_data;

--3. Who are the top 10% highest spenders?
with highest_spenders as(
		select "id", sum(amtliq + amtvege +amtnonveg+amtpes+ amtchocolates +amtcomm) as customer_spent
		from marketing_data
		group by "id") ,

	rank_top_ten_pct as(
		select "id", customer_spent, Ntile(10) over(order by customer_spent DESC) as top_tier
		from highest_spenders)

select "id", customer_spent
from rank_top_ten_pct
where top_tier=1;

--4. Which country generates the highest total revenue?
select country, sum(amtliq + amtvege +amtnonveg+amtpes+ amtchocolates +amtcomm) as country_total
from marketing_data
group by country
order by country_total DESC
limit 1;
		 
--5. What is the revenue contribution (%) by each country?	
with country_rev as(
	select 
		country, 
		sum(amtliq + amtvege +amtnonveg+amtpes+ amtchocolates +amtcomm) as Total_rev
	from marketing_data
	group by country),

	rev_pct as(
		select country, 
			round(Total_rev *100/ sum(Total_rev) over(),2) as country_rev_pct
		from country_rev)
select country, 
		country_rev_pct
		from rev_pct
		ORDER BY country_rev_pct DESC;

		
---------------	Campaign Effectiveness

--6. How many customers responded to each ad channel?

with customer_response as(
	select 
		m."id",
		m.response,
		a.bulkmail_ad,
		a.twitter_ad,
		a.instagram_ad,
		a.facebook_ad,
		a.brochure_ad
	from marketing_data m
	join ad_data a on m.id =a.id
	where m.response =1)

select
	sum(bulkmail_ad) as total_bulkmail_ads,
	sum(twitter_ad) as total_twitter_ads,
	sum(instagram_ad) as total_intragram_ads,
	sum(facebook_ad) as total_facebook_ads,
	sum(brochure_ad) as total_brochure_ads
from customer_response;
	


--7. What is the response rate per channel?
With customer_response_rate as (
   select
   		round(sum(case when m.response = 1 then a.bulkmail_ad else 0 end)* 100/ count(*), 2) as bulkmail_res_rate,
		round(sum(case when m.response =1 then a.twitter_ad else 0 end)* 100/count(*), 2) as twitter_res_rate,
		round(sum(case when m.response =1 then a.instagram_ad else 0 end) * 100/count(*),2) as instagram_res_rate,
		round(sum(case when m.response =1 then a.facebook_ad else 0 end)*100/count(*),2) as facebook_res_rate,
		round(sum(case when m.response =1 then a.brochure_ad else 0 end)* 100/count(*),2) as brochure_res_rate
		
    from marketing_data m
	join ad_data a on m.id= a.id
	
)
select *
from customer_response_rate;

--8. Which ad channel generated the highest total revenue?

with total_revenue as(
 	select m."id", m.response,
 		(amtliq + amtvege +amtnonveg+amtpes+ amtchocolates +amtcomm) as total_rev
	from marketing_data	m
),
ad_rev as(
	select 
		round(sum(case when t.response = 1 and a.bulkmail_ad =1 then total_rev else 0 end),2) as bulkmail_rev,
		round(sum(case when t.response =1 and a.twitter_ad =1 then total_rev else 0 end), 2) as twitter_rev,
		round(sum(case when t.response =1 and  a.instagram_ad =1 then total_rev else 0 end),2) as instagram_rev,	
		round(sum(case when t.response =1 and a.facebook_ad =1 then total_rev else 0 end),2) as facebook_rev,	
		round(sum(case when t.response =1 and a.brochure_ad =1  then total_rev else 0 end),2) as brochure_rev
		
    from total_revenue t
	join ad_data a on t."id"= a."id"
	)

select 'Bulk Mail' as ad_channel, bulkmail_rev as revenue from ad_rev
union all
select  'Twitter', twitter_rev from ad_rev
union all
select  'Instagram', instagram_rev from ad_rev
union all
select  'Facebook', facebook_rev from ad_rev
union all
select 'Brochure', brochure_rev from ad_rev
order by revenue DESC
limit 1;




--9. What is the average spending per responder per channel?

with total_revenue as(
 	select m."id", m.response,
 		(amtliq + amtvege +amtnonveg+amtpes+ amtchocolates +amtcomm) as total_rev
	from marketing_data	m
),
avg_ad_rev as(
	select 
		round(avg(case when t.response = 1 and a.bulkmail_ad =1 then total_rev end),2) as avg_bulkmail_rev,
		round(avg(case when t.response =1 and a.twitter_ad =1 then total_rev end), 2) as avg_twitter_rev,
		round(avg(case when t.response =1 and  a.instagram_ad =1 then total_rev end),2) as avg_instagram_rev,	
		round(avg(case when t.response =1 and a.facebook_ad =1 then total_rev end),2) as avg_facebook_rev,	
		round(avg(case when t.response =1 and a.brochure_ad =1  then total_rev end),2) as avg_brochure_rev
		
    from total_revenue t
	join ad_data a on t."id"= a."id"
	)

	
select * from avg_ad_rev;



--10. Which ad channel has the highest ROI(avg spending per responder)?
with customer_avg_spending as (
    select
        m.id,
        m.response,
        (m.amtliq + m.amtvege + m.amtnonveg + 
         m.amtpes + m.amtchocolates + m.amtcomm) AS total_revenue,
        a.bulkmail_ad,
        a.twitter_ad,
        a.instagram_ad,
        a.facebook_ad,
        a.brochure_ad
    from marketing_data m
    join ad_data a on m.id = a.id
),

channel_avg as (
    select 'Bulk Mail' as channel, avg(case when bulkmail_ad = 1 and response = 1 then total_revenue end) as avg_spending
    from customer_avg_spending
    union all
    select 'Twitter', avg(case when twitter_ad = 1 and response = 1 then total_revenue end)
    from customer_avg_spending
    union all
    select 'Instagram', avg(case when instagram_ad = 1 and response = 1 then total_revenue end)
    from customer_avg_spending
    union all
    select 'Facebook', avg(case when facebook_ad = 1 and response = 1 then total_revenue end)
    FROM customer_avg_spending
    UNION ALL
    select 'Brochure', avg(case when brochure_ad = 1 and response = 1 then total_revenue end)
    from customer_avg_spending
),

channel_rank as (
 
    select 
        channel,
        avg_spending,
        rank() over (order by avg_spending DESC) as roi_rank
    FROM channel_avg
)
select *
from channel_rank
order by roi_rank;


---------------------- Geographic Insights

--11. Which country has the highest ad engagement rate?
with customer_info as(
	select
		 m.id,
        m.country,
        a.bulkmail_ad,
        a.twitter_ad,
        a.instagram_ad,
        a.facebook_ad,
        a.brochure_ad
    from marketing_data m
    join ad_data a on m.id = a.id
),
	country_eng as(
	select
		country,
		sum(case when bulkmail_ad =1 or
						  facebook_ad =1 or
						  brochure_ad =1 or
						  twitter_ad =1 or
						  instagram_ad=1 then 1 else 0 end) *100/count(*) as country_engagement_rate
	from customer_info
	group by country
)
select
	country,
	country_engagement_rate,
	rank()over(order by country_engagement_rate DESC) as engegment_rank
	from country_eng;



---12. Which country generates the most revenue from Facebook responders?
with customer_data as(
	select
		m.country,
		m.response,
		a.facebook_ad,
		(m.amtliq + m.amtvege + m.amtnonveg + m.amtpes + m.amtchocolates + m.amtcomm) AS total_revenue
	from marketing_data m
	join ad_data a on m."id" = a.id
)
	
select 
	country,
	sum(case when response =1 and facebook_ad =1 then total_revenue end) as facebook_revenue
from customer_data
group by country
order by facebook_revenue DESC;
	

---13. What is the preferred ad channel per country?
with customer_info as(
	select
        m.country,
		m.response,
        a.bulkmail_ad,
        a.twitter_ad,
        a.instagram_ad,
        a.facebook_ad,
        a.brochure_ad
    from marketing_data m
    join ad_data a on m.id = a.id
),
	
	preferred_ad_ch as (
		select country, 'bulkmail' as channel,
		sum(case when response =1 and bulkmail_ad =1 then 1 else 0 end) as responses
		from customer_info
		group by country

		union all

		select country, 'twitter' as channel,
			sum(case when response = 1 and twitter_ad =1 then 1 else 0 end)
		from customer_info
		group by country

		Union all

		select country, 'instagram' as channel,
		sum(case when response = 1 and instagram_ad =1 then 1 else 0 end)
		from customer_info
		group by country

		union all

		select country, 'facebook' as channel,
		sum(case when response =1 and facebook_ad = 1 then 1 else 0 end)
		from customer_info	
		group by country

		union all 
		select country, 'brochure' as channel,
		sum(case when response = 1 and brochure_ad = 1 then 1 else 0 end)
		from customer_info
		group by country
	),
	rank_country as( select country, responses, channel,
		rank() over(partition by country order by responses DESC) as channel_rank
		from preferred_ad_ch)

select country, channel, responses, channel_rank 
from rank_country;
		

----------------------- Customer Segmentation

--15. Which age group responds most to social media ads?

select 
	case
		when extract(year from current_date) - year_birth between 29 and 39 then '29-39'
		when extract(year from current_date) -year_birth between 40 and 50 then '40-50'
		when extract(year from current_date)- year_birth between 51 and 61 then '51-61'
		when extract(year from current_date)- year_birth between 62 and 72 then '62-72'
		when extract(year from current_date) -year_birth between 73 and 132 then 'senior' end as age_group,
		
	count(*) as total_responses
from marketing_data m
join ad_data a 
on m.id = a.id
where m.response = 1
group by age_group
order by total_responses DESC;



---16. Do younger customers prefer Instagram?

select
	case when extract(year from current_date)- year_birth <35 then 'younger_customer' else  'older_customers' end as age_groups,
	sum(a.instagram_ad) as instgram_responses
	from marketing_data m
	join ad_data a on m.id = a.id
	group by age_groups;

---17. Are seniors more responsive to brochure ads?

select 
	case when extract(year from current_date)-year_birth >=60 then 'seniors' else 'non_seniors' end as age_groups,
	sum(a.brochure_ad) as brochure_responses
	from marketing_data m
	join ad_data a on m.id=a.id
	group by age_groups;
	
----18. Which education level has highest engagement rate?
select education, 
	count(*) as total_customers,
	sum(a.bulkmail_ad + a.twitter_ad + a.instagram_ad +
    a.facebook_ad + a.brochure_ad) as total_engagement,
	
	round(sum(a.bulkmail_ad + a.twitter_ad + a.instagram_ad +
        a.facebook_ad + a.brochure_ad)::numeric / count(*), 2) as engagement_rate
from marketing_data m
join ad_data a on m.id =a.id
group by education
order by engagement_rate DESC;

-- 19. Which marital status group spends the most after responding?

select 
	marital_status, 
	sum(amtliq + amtvege + amtnonveg + amtpes + amtchocolates + amtcomm) as total_spent
from marketing_data
where response =1
group by marital_status
order by total_spent DESC;


---20. Identify high-income customers not responding to any ads.

select *
from marketing_data
where response =0
	and income> (select percentile_cont(0.75)
							within group(order by income)
					from marketing_data
					where response =0)

-------------------- further analysis of high-income customers who did not respond to any ads
select
    m.id,
    m.Income,
    m.amtliq + m.amtvege + m.amtnonveg + m.amtpes + m.amtchocolates + m.amtcomm as total_spending
from marketing_data m
join ad_data a
    on m.id = a.id
where m.Income > (select percentile_cont(0.75)
							within group(order by income)
					from marketing_data)
  and a.bulkmail_ad = 0
  and a.twitter_ad = 0
  and a.instagram_ad = 0
  and a.facebook_ad = 0
  and a.brochure_ad = 0
  and  m.response = 0
order by total_spending DESC;

--------------------- Engagement Analysis

----21. How many ads did each customer respond to?
select
    m.id,
    m.Year_Birth,
    m.Education,
    m.Marital_Status,
    a.bulkmail_ad,
    a.twitter_ad,
    a.instagram_ad,
    a.facebook_ad,
    a.brochure_ad,
    m.Response,
    (a.bulkmail_ad + a.twitter_ad + a.instagram_ad + a.facebook_ad + a.brochure_ad + m.response) as total_ads_responded

from marketing_data m
join ad_data a on m.id = a.id
order by total_ads_responded DESC;


----22. Classify engagement level:
--* 0 ads → No Engagement
--* 1–2 ads → Low
--* 3+ ads → High

with customer_response as(select
    m.id,
    m.response,
    (a.bulkmail_ad + a.twitter_ad + a.instagram_ad + a.facebook_ad + a.brochure_ad + m.response) as total_ad_responded

from marketing_data m
join ad_data a on m.id = a.id),

	customer_engagement as(
		select 
			count(case when total_ad_responded =0 then 1 end) as no_engagemnt,
			count(case when total_ad_responded between 1 and 2 then 1 end) as low_engagement,
			count(case when total_ad_responded>= 3 then 1 end) as high_engagment
	from customer_response
	)	
select * from customer_engagement;
		

---23. Do high-engagement customers spend more?

with customer_response as(select
    m.response,  m."id",
    (a.bulkmail_ad + a.twitter_ad + a.instagram_ad + a.facebook_ad + a.brochure_ad + m.response) as total_ad_responded,
	sum(m.amtliq + m.amtvege + m.amtnonveg + m.amtpes + m.amtchocolates + m.amtcomm) as total_spent
from marketing_data m
join ad_data a on m.id = a.id

group by m.id, m.response,
             a.bulkmail_ad, a.twitter_ad, a.instagram_ad, a.facebook_ad, a.brochure_ad),
			 
	customer_engagement as(
		select 
			"id",
			total_spent,
			case 
				when total_ad_responded =0 then 'no_engagemnt'
				when total_ad_responded between 1 and 2 then 'low_engagement'
				when total_ad_responded>= 3 then 'high_engagement' end as customer_engagement_level
	from customer_response
	)
select
    customer_engagement_level,
    count(*) as num_customers,
    avg(total_spent) as avg_spent,
    sum(total_spent) as total_spent
from customer_engagement
group by customer_engagement_level
order by avg_spent DESC;

--24. Do customers responding to highest number of ads generate more revenue?
with customer_response as(select
    m.response,  m."id",
    (a.bulkmail_ad + a.twitter_ad + a.instagram_ad + a.facebook_ad + a.brochure_ad + m.response) as total_ad_responded,
	(m.amtliq + m.amtvege + m.amtnonveg + m.amtpes + m.amtchocolates + m.amtcomm) as total_spent
from marketing_data m
join ad_data a on m.id = a.id
),
	ad_engagement as(select
		"id",
		total_spent,
		case
			when total_ad_responded =5 then 'responded_to_all_ads' else 'responded_non_or_more_than_one' end as engagement_level
		from customer_response
	)
	
select
	engagement_level,
	count(*) as num_customers,
	avg(total_spent) as avg_spent,
	sum(total_spent) as total_spent
from ad_engagement
group by engagement_level
order by num_customers
	
--25. Identify customers who responded to highest number of ads campaignes.

select
    m.id
from marketing_data m
join ad_data a on m.id = a.id
where (a.bulkmail_ad + a.twitter_ad + a.instagram_ad + a.facebook_ad + a.brochure_ad + m.response) = 5;



--26. Rank customers by spending within each country.

with customer_country as(
	select "id", country,  sum(amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm) as customer_spending
	from marketing_data
	group by "id", country
),
	customer_rank as(
		select "id", country, customer_spending,
			rank() over(partition by country order by customer_spending DESC) as customer_rank
		from customer_country)
select country, "id", customer_spending, customer_rank
from customer_rank;

		

---27. Find customers spending above their country average.

select "id", (amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm) as customer_spending
from marketing_data m
where (amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm) > (select avg(amtliq + amtvege + amtnonveg + 
         amtpes + amtchocolates + amtcomm) as avg_customer_spending_by_country
							from marketing_data
							
							where country = m.country)
							
order by customer_spending;

